import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Top Nav (shared) */}
        <nav className="fixed top-0 left-0 right-0 z-50 flex items-center justify-end px-4 sm:px-8 py-4 bg-black border-b border-gray-800">
          <div className="flex items-center gap-4 text-sm">
            <a href="/#learn-more" className="text-gray-200 hover:text-white">Learn more</a>
            <a href="/team" className="text-gray-200 hover:text-white">Team</a>
            <a href="/careers" className="text-gray-200 hover:text-white">Careers</a>
            <a href="/blog" className="text-gray-200 hover:text-white">Blog</a>
            <a
              href="https://calendly.com/chris-kelly-stanford/1-1"
              target="_blank"
              rel="noopener noreferrer"
              className="px-4 py-2 bg-purple-800 text-white rounded-full font-semibold border border-purple-900 hover:bg-purple-900 transition"
            >
              Book a Demo
            </a>
          </div>
        </nav>
        {/* Spacer to offset fixed nav height */}
        <div className="h-14" />
        {children}
      </body>
    </html>
  );
}
